name: AzureARMDeploy

on:
  push: 
    branches: [main]
  
  pull_request: 
    branches: [main]
  
  workflow_dispatch:

jobs: 
  deploy:   
   runs-on: ubuntu-latest

   steps: 
   - name: login to azure
     uses: azure/login@v1
     with:
      creds: '${{ secrets.AZURE_CREDENTIALS }}'

   - name: checkout source
     uses: actions/checkout@v2

   - name: Azure CLI script
     uses: azure/CLI@v1
     with:
      azcliversion: 2.30.0
      inlineScript: |
        az account show
        az deployment group create \
        --name ExampleDeployment \
        --resource-group DOE-India-VM \
        --template-file armtemplates/webapp-windows.json \
        --parameters webSiteName="${{vars.APPSERVICENAME1}}" hostingPlanName="${{vars.HOSTINGPLANNAME}}" skuName="S1" location="eastus2" skuCapacity="1"


    
